name: Build on Tag

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      
    - name: Checkout kernel source
      uses: actions/checkout@v2    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: whyred
        USE_CCACHE: 1
        
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: whyred_defconfig
        image: Image.gz-dtb
        
    - name: upload
      uses: actions/upload-artifact@v3
      with:
         path: ${{ steps.build.outputs.outfile }}
         
